# Generated by Django 3.0.4 on 2020-03-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20200324_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
