# Generated by Django 3.0.4 on 2020-04-06 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_remove_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(null=True, upload_to='candidates'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jedi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='admission.Jedi'),
        ),
    ]
